FROM nikolaik/python-nodejs

WORKDIR /app

RUN apt-get update -qqy && \
    apt-get install -y parallel && \
    apt-get install -y libasound2 && \
    pip install -U lxml

ADD scripts/server.sh ./scripts/server.sh
ADD assets ./assets
ADD package.json ./
ADD src ./src

RUN yarn install --production

EXPOSE 8000
EXPOSE 3000

CMD [ "sh", "scripts/server.sh"]
