FROM nikolaik/python-nodejs

WORKDIR /app

RUN apt-get update -qqy && \
    apt-get install -y parallel && \
    apt-get install -y libasound2 && \
    pip install -U lxml

ADD scripts/add.sh ./scripts/add.sh
ADD assets ./assets
ADD package.json ./
ADD src ./src

RUN yarn install --production

CMD [ "sh", "scripts/add.sh"]