version: "3"
services:
  torrent:
    restart: always
    image: torrent
    container_name: torrent
    build:
      context: ./
      dockerfile: Dockerfile.torrent
    env_file: 
      - ./.env.compose
    ports:
      - 8000:8000
      - 3000:3000
    logging:
      driver: "json-file" 
      options:
        tag: torrent 
    networks:
      - hse-master-thesis-webrtc-speed-test_webtorrent

  seed:
    image: seed
    container_name: seed
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.seed
    env_file: 
      - ./.env.compose
    logging:
      driver: "json-file" 
      options:
        tag: seed 
    depends_on:
      - torrent
    networks:
      - hse-master-thesis-webrtc-speed-test_webtorrent
 
  add:
    image: add
    container_name: add
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.add
    env_file: 
      - ./.env.compose
    logging:
      driver: "json-file" 
      options:
        tag: add
    depends_on:
      - torrent
      - seed
    networks:
      - hse-master-thesis-webrtc-speed-test_webtorrent

networks:
  hse-master-thesis-webrtc-speed-test_webtorrent:
